### ISSUE TITLE
Font weights in Homepage don't match our mockup

### ISSUE THREAD

**Issue by willwull** [WatchItTeam/WatchIt#27]
Should be
```css
#homepage {
  margin-left: 45px;

  h1 {
    font-size: 36px;
    font-weight: 800; <--- add this
  }

  h2 {
    font-size: 24px;
    font-weight: normal; <--- add this
  }
}
```
