### ISSUE TITLE
iOS style issues

### ISSUE THREAD

**Issue by willwull** [WatchItTeam/WatchIt#52]
There is a black overlay that appears on the screen when closing the sidebar on iOS.
To fix (`App.scss`):

```scss
#overlay {
  // see responsive.scss
  display: none;
  z-index: $overlay-z;

  // removes the black overlay that iOS puts on top of clickable items  <----
  -webkit-tap-highlight-color: rgba(0,0,0,0);  // <---- add these two lines
}
```

Buttons have different size on iOS compared to desktop.
Fix (`index.scss`):

```scss
button {
  -webkit-appearance: none; // remove default iOS styling
  cursor: pointer;
  border: none;
  background: none;
  color: inherit;
  border-radius: 0;
  padding: 0; // <----------- add this line

  &:active { color: black; }
}
```

I discovered these issues while implementing search, but they should probably be their own PR.
